"""Conservation-audited zero-dimensional plasma-reactor building blocks.

The package separates universal bookkeeping (species, reactions, geometry,
units) from chemistry decks and equipment-specific closures.  A global model
is only as predictive as its rate and wall-loss evidence; these classes make
that evidence and every open-system exchange explicit.
"""

from .geometry import CylindricalReactor, ElectropositiveEdgeFactors
from .argon import (
    ARGON_4S_METASTABLE_ENERGY_EV,
    ARGON_IONIZATION_ENERGY_EV,
    ARGON_METASTABLE_IONIZATION_ENERGY_EV,
    build_lee_lieberman_argon_volume_network,
    lee_lieberman_argon_species,
)
from .chlorine import (
    CHLORINE_ATOM_MASS_AMU,
    CHLORINE_MOLECULE_MASS_AMU,
    build_lee_lieberman_chlorine_particle_network,
    lee_lieberman_chlorine_species,
)
from .chlorine_wall import (
    WALL_RECOMBINATION_EVIDENCE_KINDS,
    ChlorineWallFlux,
    ChlorineWallRecombinationBoundary,
    chlorine_atom_mean_thermal_speed_m_s,
)
from .evaluated_chlorine import (
    ATOMIC_CHLORINE_IONIZATION_THRESHOLD_EV,
    HAMILTON_2018_CL2_DISSOCIATION_STATES,
    MOLECULAR_CHLORINE_TOTAL_IONIZATION_THRESHOLD_EV,
    hamilton_2018_cl2_state_dissociation_rates,
    hamilton_2018_cl2_state_dissociation_reactions,
    nist_hayes_atomic_chlorine_ionization_rate,
    nist_molecular_chlorine_total_ionization_rate,
)
from .network import (
    CM3_TO_M3,
    E_CHARGE_C,
    ELECTRON_MASS_KG,
    ConstantRateCoefficient,
    ElectronArrheniusRateCoefficient,
    ElectronInverseTemperaturePolynomialRateCoefficient,
    ElectronBase10LogPolynomialRateCoefficient,
    ElectronMaxwellianCrossSectionRateCoefficient,
    ElectronTemperatureTabulatedRateCoefficient,
    RateContext,
    Reaction,
    ReactionNetwork,
    Species,
)
from .model import (
    ArgonGlobalCondition,
    ArgonGlobalSolution,
    ArgonTransportProvider,
    ArgonTransportState,
    FixedArgonTransportProvider,
    LeeLiebermanArgonGlobalModel,
    PASCAL_PER_MTORR,
)
from .power import (
    POWER_EVIDENCE_KINDS,
    PREDICTIVE_EVIDENCE_KINDS,
    AbsorbedPowerEstimate,
    DirectDriveRFPowerBoundary,
    MatchedRFPowerBoundary,
    MeasuredAbsorbedPowerBoundary,
    time_average_real_power_W,
)
from .transport import (
    ARGON_MASS_KG,
    ATOMIC_MASS_UNIT_KG,
    STANDARD_PRESSURE_PA,
    LeeLiebermanArgonTransportProvider,
    argon_relative_temperature_eV,
    lee_lieberman_argon_ion_temperature_eV,
    nist_argon_self_diffusion_m2_s,
    phelps_argon_momentum_transfer_cross_section_m2,
    phelps_argon_momentum_transfer_rate_m3_s,
)

__all__ = [
    "CM3_TO_M3",
    "E_CHARGE_C",
    "ELECTRON_MASS_KG",
    "ATOMIC_CHLORINE_IONIZATION_THRESHOLD_EV",
    "HAMILTON_2018_CL2_DISSOCIATION_STATES",
    "MOLECULAR_CHLORINE_TOTAL_IONIZATION_THRESHOLD_EV",
    "ARGON_4S_METASTABLE_ENERGY_EV",
    "ARGON_IONIZATION_ENERGY_EV",
    "ARGON_METASTABLE_IONIZATION_ENERGY_EV",
    "ARGON_MASS_KG",
    "ATOMIC_MASS_UNIT_KG",
    "CHLORINE_ATOM_MASS_AMU",
    "CHLORINE_MOLECULE_MASS_AMU",
    "ChlorineWallFlux",
    "ChlorineWallRecombinationBoundary",
    "ArgonGlobalCondition",
    "ArgonGlobalSolution",
    "ArgonTransportProvider",
    "ArgonTransportState",
    "AbsorbedPowerEstimate",
    "ConstantRateCoefficient",
    "CylindricalReactor",
    "ElectronArrheniusRateCoefficient",
    "ElectronInverseTemperaturePolynomialRateCoefficient",
    "ElectronBase10LogPolynomialRateCoefficient",
    "ElectronMaxwellianCrossSectionRateCoefficient",
    "ElectronTemperatureTabulatedRateCoefficient",
    "ElectropositiveEdgeFactors",
    "FixedArgonTransportProvider",
    "DirectDriveRFPowerBoundary",
    "LeeLiebermanArgonGlobalModel",
    "LeeLiebermanArgonTransportProvider",
    "MatchedRFPowerBoundary",
    "MeasuredAbsorbedPowerBoundary",
    "PASCAL_PER_MTORR",
    "POWER_EVIDENCE_KINDS",
    "PREDICTIVE_EVIDENCE_KINDS",
    "RateContext",
    "Reaction",
    "ReactionNetwork",
    "Species",
    "STANDARD_PRESSURE_PA",
    "WALL_RECOMBINATION_EVIDENCE_KINDS",
    "argon_relative_temperature_eV",
    "build_lee_lieberman_argon_volume_network",
    "build_lee_lieberman_chlorine_particle_network",
    "chlorine_atom_mean_thermal_speed_m_s",
    "hamilton_2018_cl2_state_dissociation_rates",
    "hamilton_2018_cl2_state_dissociation_reactions",
    "lee_lieberman_argon_species",
    "lee_lieberman_chlorine_species",
    "lee_lieberman_argon_ion_temperature_eV",
    "nist_argon_self_diffusion_m2_s",
    "nist_hayes_atomic_chlorine_ionization_rate",
    "nist_molecular_chlorine_total_ionization_rate",
    "phelps_argon_momentum_transfer_cross_section_m2",
    "phelps_argon_momentum_transfer_rate_m3_s",
    "time_average_real_power_W",
]
