#!/usr/bin/env python3
"""Calibration audit for the preregistered Bosch v8 ion-boundary map.

The expensive reactor and exact surface recurrence are tabulated over frozen
wall-loss and local-ion-factor nodes. Map fitting then queries the local surface
response at the current-conserving ion factor generated by the cylindrical
Zernike operator. The chronological heldout outcome asset is never loaded.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, replace
from hashlib import sha256
import json
import math
from pathlib import Path
import sys

import numpy as np
from scipy.interpolate import PchipInterpolator


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from petch.bosch_wafer_depth import (  # noqa: E402
    build_bosch_reference_surface_mechanisms,
)
from petch.bosch_wafer_depth_fast import (  # noqa: E402
    predict_bosch_wafer_point_depth_batch_fast,
)
from petch.reactor_global.bosch_spts_cylindrical import (  # noqa: E402
    BoschSPTSCylindricalParameters,
    DeterministicBoschSPTSCylindricalReactorToWafer,
)
from scripts.audit_bosch_dynamic_wall_calibration import (  # noqa: E402
    _Prediction,
    _inputs,
    _wall_nodes,
)
from scripts.audit_bosch_wall_conditioning_calibration import (  # noqa: E402
    BASE_CYLINDRICAL_KEYWORDS,
    BASE_REDUCED_PARAMETERS,
)


V8_DIRECTORY = (
    ROOT / "results" / "curated"
    / "zenodo_bosch_wafer_boundary_map_depth_extension_v8"
)
PREREGISTRATION = V8_DIRECTORY / "preregistration.json"
RESPONSE_TABLE = V8_DIRECTORY / "exact_wall_ion_response_table.npz"
OUTPUT = V8_DIRECTORY / "calibration_fit.json"
_LOG_FOUR = math.log(4.0)


def _hash(path):
    return sha256(Path(path).read_bytes()).hexdigest()


def _load_preregistration():
    payload = json.loads(PREREGISTRATION.read_text(encoding="utf-8"))
    exposure = payload["calibration_exposure"]
    firewall = payload["target_firewall"]
    if (
        exposure["v8_operator_implemented_before_this_freeze"] is not False
        or exposure["v8_response_table_started_before_this_freeze"] is not False
        or exposure["v8_fit_started_before_this_freeze"] is not False
        or exposure["heldout_outcomes_examined"] is not False
        or firewall["heldout_outcomes_read_at_freeze"] is not False
    ):
        raise RuntimeError("Bosch v8 target firewall is not closed")
    expected = payload["input_hashes"]
    paths = {
        "v7_preregistration_json": (
            ROOT / "results" / "curated"
            / "zenodo_bosch_recipe_path_memory_depth_extension_v7"
            / "preregistration.json"),
        "v7_calibration_fit": (
            ROOT / "results" / "curated"
            / "zenodo_bosch_recipe_path_memory_depth_extension_v7"
            / "calibration_fit.json"),
        "v7_exact_response_table": (
            ROOT / "results" / "curated"
            / "zenodo_bosch_recipe_path_memory_depth_extension_v7"
            / "exact_response_table.npz"),
        "v7_spatial_residual_discovery": (
            ROOT / "results" / "curated"
            / "zenodo_bosch_recipe_path_memory_depth_extension_v7"
            / "spatial_residual_discovery.json"),
        "process_data": (
            ROOT / "data" / "experimental" / "zenodo_17122442"
            / "Process_data.nc"),
        "process_dictionary": (
            ROOT / "data" / "experimental" / "zenodo_17122442"
            / "Dictionary_process.nc"),
        "calibration_measurements": (
            ROOT / "data" / "experimental" / "zenodo_17122442"
            / "calibration_Si_Oxide_etch_89_points.csv"),
    }
    mismatches = {
        key: {"expected": expected[key], "actual": _hash(path)}
        for key, path in paths.items() if _hash(path) != expected[key]
    }
    if mismatches:
        raise RuntimeError(f"Bosch v8 frozen input hash mismatch: {mismatches}")
    return payload


def _nodes(count=13):
    return _wall_nodes(count)


def _evaluate_pchip_coefficients(coefficients, nodes, query, leading_shape):
    """Evaluate stored PCHIP pieces at one query per leading-shape element."""
    coefficients = np.asarray(coefficients, dtype=float)
    nodes = np.asarray(nodes, dtype=float)
    query = np.asarray(query, dtype=float)
    if query.shape != tuple(leading_shape):
        raise ValueError("PCHIP query shape does not match its response axes")
    interval = np.searchsorted(nodes, query, side="right") - 1
    interval = np.clip(interval, 0, nodes.size - 2)
    delta = query - nodes[interval]
    index = np.indices(query.shape)
    selected = tuple(index[axis] for axis in range(query.ndim))
    c0 = coefficients[(0, interval) + selected]
    c1 = coefficients[(1, interval) + selected]
    c2 = coefficients[(2, interval) + selected]
    c3 = coefficients[(3, interval) + selected]
    value = ((c0 * delta + c1) * delta + c2) * delta + c3
    derivative = (3.0 * c0 * delta + 2.0 * c1) * delta + c2
    return value, derivative


@dataclass(frozen=True)
class BoschConditionedIonResponse:
    """Exact-wall slice with fast local-ion PCHIP evaluation."""

    experiment_keys: tuple[str, ...]
    log_ion_factor_nodes: np.ndarray
    silicon_depth_m: np.ndarray
    oxide_loss_m: np.ndarray

    def __post_init__(self):
        keys = tuple(str(value) for value in self.experiment_keys)
        nodes = np.asarray(self.log_ion_factor_nodes, dtype=float).copy()
        silicon = np.asarray(self.silicon_depth_m, dtype=float).copy()
        oxide = np.asarray(self.oxide_loss_m, dtype=float).copy()
        expected = (nodes.size, len(keys), 89)
        if (
            len(keys) == 0
            or len(keys) != len(set(keys))
            or nodes.ndim != 1
            or nodes.size != 13
            or silicon.shape != expected
            or oxide.shape != expected
            or np.any(~np.isfinite(nodes))
            or np.any(np.diff(nodes) <= 0.0)
            or nodes[0] != -_LOG_FOUR
            or nodes[-1] != _LOG_FOUR
            or np.any(~np.isfinite(silicon))
            or np.any(~np.isfinite(oxide))
            or np.any(silicon < 0.0)
            or np.any(oxide < 0.0)
        ):
            raise ValueError("invalid conditioned Bosch local-ion response")
        for value in (nodes, silicon, oxide):
            value.setflags(write=False)
        object.__setattr__(self, "experiment_keys", keys)
        object.__setattr__(self, "log_ion_factor_nodes", nodes)
        object.__setattr__(self, "silicon_depth_m", silicon)
        object.__setattr__(self, "oxide_loss_m", oxide)

    def evaluate(self, ion_factor):
        factor = np.asarray(ion_factor, dtype=float)
        expected = (len(self.experiment_keys), 89)
        if (
            factor.shape != expected
            or np.any(~np.isfinite(factor))
            or np.any(factor < 0.25)
            or np.any(factor > 4.0)
        ):
            raise ValueError("invalid Bosch local ion-factor query")
        query = np.log(factor)
        silicon_interpolator = PchipInterpolator(
            self.log_ion_factor_nodes, self.silicon_depth_m, axis=0)
        oxide_interpolator = PchipInterpolator(
            self.log_ion_factor_nodes, self.oxide_loss_m, axis=0)
        silicon, silicon_derivative = _evaluate_pchip_coefficients(
            silicon_interpolator.c,
            self.log_ion_factor_nodes,
            query,
            expected,
        )
        oxide, oxide_derivative = _evaluate_pchip_coefficients(
            oxide_interpolator.c,
            self.log_ion_factor_nodes,
            query,
            expected,
        )
        predictions = tuple(
            _Prediction(
                silicon_depth_m=silicon[index],
                oxide_loss_m=oxide[index],
            )
            for index in range(len(self.experiment_keys))
        )
        return predictions, silicon_derivative, oxide_derivative


@dataclass(frozen=True)
class BoschExactWallIonResponseTable:
    """Exact reactor/surface responses on the frozen two-axis tensor grid."""

    experiment_keys: tuple[str, ...]
    log_wall_multiplier_nodes: np.ndarray
    log_ion_factor_nodes: np.ndarray
    silicon_depth_m: np.ndarray
    oxide_loss_m: np.ndarray

    def __post_init__(self):
        keys = tuple(str(value) for value in self.experiment_keys)
        wall = np.asarray(self.log_wall_multiplier_nodes, dtype=float).copy()
        ion = np.asarray(self.log_ion_factor_nodes, dtype=float).copy()
        silicon = np.asarray(self.silicon_depth_m, dtype=float).copy()
        oxide = np.asarray(self.oxide_loss_m, dtype=float).copy()
        expected = (wall.size, ion.size, len(keys), 89)
        if (
            len(keys) == 0
            or len(keys) != len(set(keys))
            or wall.shape != (13,)
            or ion.shape != (13,)
            or silicon.shape != expected
            or oxide.shape != expected
            or any(np.any(~np.isfinite(value)) for value in (
                wall, ion, silicon, oxide))
            or np.any(np.diff(wall) <= 0.0)
            or np.any(np.diff(ion) <= 0.0)
            or wall[0] != -_LOG_FOUR
            or wall[-1] != _LOG_FOUR
            or ion[0] != -_LOG_FOUR
            or ion[-1] != _LOG_FOUR
            or np.any(silicon < 0.0)
            or np.any(oxide < 0.0)
        ):
            raise ValueError("invalid Bosch exact wall-ion response table")
        for value in (wall, ion, silicon, oxide):
            value.setflags(write=False)
        object.__setattr__(self, "experiment_keys", keys)
        object.__setattr__(self, "log_wall_multiplier_nodes", wall)
        object.__setattr__(self, "log_ion_factor_nodes", ion)
        object.__setattr__(self, "silicon_depth_m", silicon)
        object.__setattr__(self, "oxide_loss_m", oxide)

    def condition_on_wall(self, wall_multipliers):
        multiplier = np.asarray(wall_multipliers, dtype=float)
        if (
            multiplier.shape != (len(self.experiment_keys),)
            or np.any(~np.isfinite(multiplier))
            or np.any(multiplier < 0.25)
            or np.any(multiplier > 4.0)
        ):
            raise ValueError("invalid Bosch wall-multiplier query")
        query = np.log(multiplier)
        silicon_interpolator = PchipInterpolator(
            self.log_wall_multiplier_nodes, self.silicon_depth_m, axis=0)
        oxide_interpolator = PchipInterpolator(
            self.log_wall_multiplier_nodes, self.oxide_loss_m, axis=0)
        silicon = np.empty(
            (self.log_ion_factor_nodes.size, len(self.experiment_keys), 89))
        oxide = np.empty_like(silicon)
        for wafer, value in enumerate(query):
            interval = int(np.clip(
                np.searchsorted(
                    self.log_wall_multiplier_nodes, value, side="right") - 1,
                0,
                self.log_wall_multiplier_nodes.size - 2,
            ))
            delta = value - self.log_wall_multiplier_nodes[interval]
            silicon[:, wafer] = np.polyval(
                silicon_interpolator.c[:, interval, :, wafer], delta)
            oxide[:, wafer] = np.polyval(
                oxide_interpolator.c[:, interval, :, wafer], delta)
        return BoschConditionedIonResponse(
            experiment_keys=self.experiment_keys,
            log_ion_factor_nodes=self.log_ion_factor_nodes,
            silicon_depth_m=silicon,
            oxide_loss_m=oxide,
        )

    def save(self, path):
        np.savez_compressed(
            path,
            experiment_keys=np.asarray(self.experiment_keys, dtype="U32"),
            log_wall_multiplier_nodes=self.log_wall_multiplier_nodes,
            log_ion_factor_nodes=self.log_ion_factor_nodes,
            silicon_depth_m=self.silicon_depth_m,
            oxide_loss_m=self.oxide_loss_m,
        )

    @classmethod
    def load(cls, path):
        with np.load(path, allow_pickle=False) as payload:
            return cls(
                experiment_keys=tuple(payload["experiment_keys"].tolist()),
                log_wall_multiplier_nodes=payload["log_wall_multiplier_nodes"],
                log_ion_factor_nodes=payload["log_ion_factor_nodes"],
                silicon_depth_m=payload["silicon_depth_m"],
                oxide_loss_m=payload["oxide_loss_m"],
            )


def _scale_local_ion_response(boundary, factor):
    factor = float(factor)
    point = np.asarray(boundary.point_flux_m2_s, dtype=float).copy()
    average = np.asarray(boundary.wafer_area_average_flux_m2_s, dtype=float).copy()
    point[:, 2] *= factor
    average[:, 2] *= factor
    return replace(
        boundary,
        point_flux_m2_s=point,
        wafer_area_average_flux_m2_s=average,
        provenance={
            **dict(boundary.provenance),
            "calibration_local_ion_factor": factor,
            "calibration_local_response_axis_only": True,
            "target_depth_used": False,
        },
    )


def _exact_responses_at_wall_multiplier(
        multiplier, measurements, trace_by_key, ion_nodes, *, workers=8):
    reduced = replace(
        BASE_REDUCED_PARAMETERS,
        neutral_wall_loss_multiplier=float(multiplier),
    )
    model = DeterministicBoschSPTSCylindricalReactorToWafer(
        BoschSPTSCylindricalParameters(
            reduced=reduced, **BASE_CYLINDRICAL_KEYWORDS))
    first = measurements[0]
    x_m = first.x_um * 1.0e-6
    y_m = first.y_um * 1.0e-6
    if any(
        not np.array_equal(item.x_um, first.x_um)
        or not np.array_equal(item.y_um, first.y_um)
        for item in measurements
    ):
        raise RuntimeError("Bosch calibration wafers do not share one map")
    response = model.source_response(x_m=x_m, y_m=y_m)

    def solve(item):
        return model.solve(
            trace_by_key[item.experiment_key],
            x_m=x_m,
            y_m=y_m,
            source_response=response,
        )

    with ThreadPoolExecutor(max_workers=int(workers)) as pool:
        boundaries = tuple(pool.map(solve, measurements))
    silicon_mechanism, oxide_mechanism = build_bosch_reference_surface_mechanisms()
    silicon = []
    oxide = []
    for log_factor in ion_nodes:
        factor = math.exp(float(log_factor))
        scaled = tuple(
            _scale_local_ion_response(boundary, factor)
            for boundary in boundaries
        )
        predictions = predict_bosch_wafer_point_depth_batch_fast(
            scaled, silicon_mechanism, oxide_mechanism)
        silicon.append(np.stack([
            item.silicon_depth_m for item in predictions]))
        oxide.append(np.stack([
            item.oxide_loss_m for item in predictions]))
    return np.stack(silicon), np.stack(oxide)


def build_response_table(*, workers=8):
    preregistration = _load_preregistration()
    measurements, process_traces, _lot_type_by_date = _inputs()
    trace_by_key = {trace.experiment_key: trace for trace in process_traces}
    wall_nodes = _nodes(
        preregistration["deterministic_acceleration"][
            "wall_chebyshev_node_count"])
    ion_nodes = _nodes(
        preregistration["deterministic_acceleration"][
            "local_ion_chebyshev_node_count"])
    silicon = []
    oxide = []
    for index, log_multiplier in enumerate(wall_nodes, start=1):
        multiplier = math.exp(float(log_multiplier))
        print(
            f"exact Bosch v8 wall node {index}/{len(wall_nodes)} "
            f"multiplier={multiplier:.9g}",
            flush=True,
        )
        node_silicon, node_oxide = _exact_responses_at_wall_multiplier(
            multiplier,
            measurements,
            trace_by_key,
            ion_nodes,
            workers=workers,
        )
        silicon.append(node_silicon)
        oxide.append(node_oxide)
    return BoschExactWallIonResponseTable(
        experiment_keys=tuple(item.experiment_key for item in measurements),
        log_wall_multiplier_nodes=wall_nodes,
        log_ion_factor_nodes=ion_nodes,
        silicon_depth_m=np.stack(silicon),
        oxide_loss_m=np.stack(oxide),
    )


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-table", action="store_true")
    parser.add_argument("--workers", type=int, default=8)
    args = parser.parse_args(argv)
    if not args.write_table:
        parser.error("the current checkpoint supports --write-table")
    table = build_response_table(workers=args.workers)
    table.save(RESPONSE_TABLE)
    print(RESPONSE_TABLE.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
