#!/usr/bin/env python3
"""Export the checksum-locked Lan--Jeon C4F6 deck for BOLSIG+ replay.

This adapter does not execute BOLSIG+ and is not part of the production
reactor path.  It produces an independent-comparator input from the exact CSV
tables consumed by petch.  The generated run requests BOLSIG+'s deterministic
density-gradient expansion at the 18 visually audited Figure-7 fields so that
bulk drift can be compared with pulsed-Townsend drift without retuning the
collision set.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

from petch.reactor_global.c4f6_electron_collisions import (
    C4F6_MASS_AMU,
    load_lan_jeon_2014_c4f6_replay,
)


ROOT = Path(__file__).resolve().parents[1]
FIGURE7_CSV = (
    ROOT / "data" / "experimental" / "lan_jeon_2014_c4f6"
    / "figure7_pure_c4f6_drift.csv"
)
DEFAULT_OUTPUT = ROOT / "results" / "scratch" / "lan_jeon_bolsig_reference"
SEPARATOR = "-" * 60


def _process_block(label, process) -> str:
    if label == "Qm":
        kind = "ELASTIC"
        third_line = f"{5.48579909065e-4 / C4F6_MASS_AMU:.17g} / mass ratio"
    elif process.kind == "ATTACHMENT":
        kind = "ATTACHMENT"
        third_line = None
    elif process.kind == "IONIZATION":
        kind = "IONIZATION"
        third_line = f"{float(process.energy_loss_eV):.17g} / threshold energy (eV)"
    else:
        kind = "EXCITATION"
        third_line = f"{float(process.energy_loss_eV):.17g} / energy loss (eV)"

    target_line = "C4F6" if label == "Qm" else f"C4F6 -> {process.product}"
    lines = [kind, target_line]
    if third_line is not None:
        lines.append(third_line)
    lines.extend((
        f"Lan--Jeon 2014 Table {'1' if label == 'Qm' else '2'} {label}",
        "doi:10.3938/jkps.64.1320",
        SEPARATOR,
    ))
    points = list(zip(process.electron_energy_eV, process.cross_section_m2))
    if label == "Qm" and points[0][0] > 0.0:
        points.insert(0, (0.0, points[0][1]))
    lines.extend(f"{energy:.17g}\t{cross_section:.17g}" for energy, cross_section in points)
    lines.append(SEPARATOR)
    return "\n".join(lines)


def collision_text() -> str:
    replay = load_lan_jeon_2014_c4f6_replay()
    blocks = [
        _process_block(label, process)
        for label, process in zip(replay.process_labels, replay.raw_deck.processes)
    ]
    return (
        "COMMENT\nC4F6\n"
        "Lan--Jeon 2014 checksum-locked source replay; generated by petch.\n"
        f"{SEPARATOR}\n\n"
        + "\n\n".join(blocks)
        + "\n"
    )


def _figure7_fields() -> tuple[float, ...]:
    with FIGURE7_CSV.open(newline="", encoding="utf-8") as stream:
        rows = tuple(csv.DictReader(stream))
    fields = tuple(float(row["reduced_electric_field_Td"]) for row in rows)
    if len(fields) != 18 or any(right <= left for left, right in zip(fields, fields[1:])):
        raise RuntimeError("Lan--Jeon Figure-7 field board topology changed")
    return fields


def instruction_text() -> str:
    run_rows = "\n".join(f"{field:.17g}" for field in _figure7_fields())
    return f"""/NOSCREEN

READCOLLISIONS
c4f6_lan_jeon.txt / File
C4F6 / Species
1 / Extrapolate

CONDITIONS
VAR / Electric field / N (Td)
0. / Angular field frequency / N (m3/s)
0. / Cosine of E-B field angle
300. / Gas temperature (K)
300. / Excitation temperature (K)
0. / Transition energy (eV)
0. / Ionization degree
1e18 / Plasma density (1/m3)
1. / Ion charge parameter
1. / Ion/neutral mass ratio
0 / e-e momentum effects
1 / Equal energy sharing
4 / Density-gradient expansion
0. / Maxwellian mean energy (eV)
800 / Number of grid points
2 / Manual parabolic grid
200. / Manual maximum energy (eV)
1e-12 / Precision
1e-7 / Convergence
4000 / Maximum iterations
1. / C4F6 fraction
1 / Normalize composition

RUN
{run_rows}

SAVERESULTS
c4f6_bulk_results.dat / File
2 / Combined format
1 / Conditions
1 / Transport coefficients
1 / Rate coefficients
0 / Reverse rate coefficients
0 / Energy loss coefficients
0 / Distribution function
0 / Skip failed runs

END
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "c4f6_lan_jeon.txt").write_text(
        collision_text(), encoding="utf-8")
    (args.output_dir / "bolsig_input.dat").write_text(
        instruction_text(), encoding="utf-8")
    print(args.output_dir)


if __name__ == "__main__":
    main()
